import { CampaignType } from './types'

// Quran Surahs data for the app
export const QURAN_SURAHS = [
  { number: 1, name: 'الفاتحة', persianName: 'فاتحه', verses: 7 },
  { number: 2, name: 'البقرة', persianName: 'بقره', verses: 286 },
  { number: 3, name: 'آل عمران', persianName: 'آل عمران', verses: 200 },
  { number: 4, name: 'النساء', persianName: 'نساء', verses: 176 },
  { number: 5, name: 'المائدة', persianName: 'مائده', verses: 120 },
  { number: 6, name: 'الأنعام', persianName: 'انعام', verses: 165 },
  { number: 7, name: 'الأعراف', persianName: 'اعراف', verses: 206 },
  { number: 8, name: 'الأنفال', persianName: 'انفال', verses: 75 },
  { number: 9, name: 'التوبة', persianName: 'توبه', verses: 129 },
  { number: 10, name: 'يونس', persianName: 'یونس', verses: 109 },
  { number: 11, name: 'هود', persianName: 'هود', verses: 123 },
  { number: 12, name: 'يوسف', persianName: 'یوسف', verses: 111 },
  { number: 13, name: 'الرعد', persianName: 'رعد', verses: 43 },
  { number: 14, name: 'إبراهيم', persianName: 'ابراهیم', verses: 52 },
  { number: 15, name: 'الحجر', persianName: 'حجر', verses: 99 },
  { number: 16, name: 'النحل', persianName: 'نحل', verses: 128 },
  { number: 17, name: 'الإسراء', persianName: 'اسراء', verses: 111 },
  { number: 18, name: 'الكهف', persianName: 'کهف', verses: 110 },
  { number: 19, name: 'مريم', persianName: 'مریم', verses: 98 },
  { number: 20, name: 'طه', persianName: 'طه', verses: 135 },
  { number: 21, name: 'الأنبياء', persianName: 'انبیاء', verses: 112 },
  { number: 22, name: 'الحج', persianName: 'حج', verses: 78 },
  { number: 23, name: 'المؤمنون', persianName: 'مؤمنون', verses: 118 },
  { number: 24, name: 'النور', persianName: 'نور', verses: 64 },
  { number: 25, name: 'الفرقان', persianName: 'فرقان', verses: 77 },
  { number: 26, name: 'الشعراء', persianName: 'شعراء', verses: 227 },
  { number: 27, name: 'النمل', persianName: 'نمل', verses: 93 },
  { number: 28, name: 'القصص', persianName: 'قصص', verses: 88 },
  { number: 29, name: 'العنكبوت', persianName: 'عنکبوت', verses: 69 },
  { number: 30, name: 'الروم', persianName: 'روم', verses: 60 },
  { number: 31, name: 'لقمان', persianName: 'لقمان', verses: 34 },
  { number: 32, name: 'السجدة', persianName: 'سجده', verses: 30 },
  { number: 33, name: 'الأحزاب', persianName: 'احزاب', verses: 73 },
  { number: 34, name: 'سبأ', persianName: 'سبأ', verses: 54 },
  { number: 35, name: 'فاطر', persianName: 'فاطر', verses: 45 },
  { number: 36, name: 'يس', persianName: 'یس', verses: 83 },
  { number: 37, name: 'الصافات', persianName: 'صافات', verses: 182 },
  { number: 38, name: 'ص', persianName: 'ص', verses: 88 },
  { number: 39, name: 'الزمر', persianName: 'زمر', verses: 75 },
  { number: 40, name: 'غافر', persianName: 'غافر', verses: 85 },
  { number: 41, name: 'فصلت', persianName: 'فصلت', verses: 54 },
  { number: 42, name: 'الشورى', persianName: 'شوری', verses: 53 },
  { number: 43, name: 'الزخرف', persianName: 'زخرف', verses: 89 },
  { number: 44, name: 'الدخان', persianName: 'دخان', verses: 59 },
  { number: 45, name: 'الجاثية', persianName: 'جاثیه', verses: 37 },
  { number: 46, name: 'الأحقاف', persianName: 'احقاف', verses: 35 },
  { number: 47, name: 'محمد', persianName: 'محمد', verses: 38 },
  { number: 48, name: 'الفتح', persianName: 'فتح', verses: 29 },
  { number: 49, name: 'الحجرات', persianName: 'حجرات', verses: 18 },
  { number: 50, name: 'ق', persianName: 'ق', verses: 45 },
  { number: 51, name: 'الذاريات', persianName: 'ذاریات', verses: 60 },
  { number: 52, name: 'الطور', persianName: 'طور', verses: 49 },
  { number: 53, name: 'النجم', persianName: 'نجم', verses: 62 },
  { number: 54, name: 'القمر', persianName: 'قمر', verses: 55 },
  { number: 55, name: 'الرحمن', persianName: 'رحمن', verses: 78 },
  { number: 56, name: 'الواقعة', persianName: 'واقعه', verses: 96 },
  { number: 57, name: 'الحديد', persianName: 'حدید', verses: 29 },
  { number: 58, name: 'المجادلة', persianName: 'مجادله', verses: 22 },
  { number: 59, name: 'الحشر', persianName: 'حشر', verses: 24 },
  { number: 60, name: 'الممتحنة', persianName: 'ممتحنه', verses: 13 },
  { number: 61, name: 'الصف', persianName: 'صف', verses: 14 },
  { number: 62, name: 'الجمعة', persianName: 'جمعه', verses: 11 },
  { number: 63, name: 'المنافقون', persianName: 'منافقون', verses: 11 },
  { number: 64, name: 'التغابن', persianName: 'تغابن', verses: 18 },
  { number: 65, name: 'الطلاق', persianName: 'طلاق', verses: 12 },
  { number: 66, name: 'التحريم', persianName: 'تحریم', verses: 12 },
  { number: 67, name: 'الملك', persianName: 'ملک', verses: 30 },
  { number: 68, name: 'القلم', persianName: 'قلم', verses: 52 },
  { number: 69, name: 'الحاقة', persianName: 'حاقه', verses: 52 },
  { number: 70, name: 'المعارج', persianName: 'معارج', verses: 44 },
  { number: 71, name: 'نوح', persianName: 'نوح', verses: 28 },
  { number: 72, name: 'الجن', persianName: 'جن', verses: 28 },
  { number: 73, name: 'المزمل', persianName: 'مزمل', verses: 20 },
  { number: 74, name: 'المدثر', persianName: 'مدثر', verses: 56 },
  { number: 75, name: 'القيامة', persianName: 'قیامه', verses: 40 },
  { number: 76, name: 'الإنسان', persianName: 'انسان', verses: 31 },
  { number: 77, name: 'المرسلات', persianName: 'مرسلات', verses: 50 },
  { number: 78, name: 'النبأ', persianName: 'نبأ', verses: 40 },
  { number: 79, name: 'النازعات', persianName: 'نازعات', verses: 46 },
  { number: 80, name: 'عبس', persianName: 'عبس', verses: 42 },
  { number: 81, name: 'التكوير', persianName: 'تکویر', verses: 29 },
  { number: 82, name: 'الانفطار', persianName: 'انفطار', verses: 19 },
  { number: 83, name: 'المطففين', persianName: 'مطففین', verses: 36 },
  { number: 84, name: 'الانشقاق', persianName: 'انشقاق', verses: 25 },
  { number: 85, name: 'البروج', persianName: 'بروج', verses: 22 },
  { number: 86, name: 'الطارق', persianName: 'طارق', verses: 17 },
  { number: 87, name: 'الأعلى', persianName: 'اعلی', verses: 19 },
  { number: 88, name: 'الغاشية', persianName: 'غاشیه', verses: 26 },
  { number: 89, name: 'الفجر', persianName: 'فجر', verses: 30 },
  { number: 90, name: 'البلد', persianName: 'بلد', verses: 20 },
  { number: 91, name: 'الشمس', persianName: 'شمس', verses: 15 },
  { number: 92, name: 'الليل', persianName: 'لیل', verses: 21 },
  { number: 93, name: 'الضحى', persianName: 'ضحی', verses: 11 },
  { number: 94, name: 'الشرح', persianName: 'شرح', verses: 8 },
  { number: 95, name: 'التين', persianName: 'تین', verses: 8 },
  { number: 96, name: 'العلق', persianName: 'علق', verses: 19 },
  { number: 97, name: 'القدر', persianName: 'قدر', verses: 5 },
  { number: 98, name: 'البينة', persianName: 'بینه', verses: 8 },
  { number: 99, name: 'الزلزلة', persianName: 'زلزله', verses: 8 },
  { number: 100, name: 'العاديات', persianName: 'عادیات', verses: 11 },
  { number: 101, name: 'القارعة', persianName: 'قارعه', verses: 11 },
  { number: 102, name: 'التكاثر', persianName: 'تکاثر', verses: 8 },
  { number: 103, name: 'العصر', persianName: 'عصر', verses: 3 },
  { number: 104, name: 'الهمزة', persianName: 'همزه', verses: 9 },
  { number: 105, name: 'الفيل', persianName: 'فیل', verses: 5 },
  { number: 106, name: 'قريش', persianName: 'قریش', verses: 4 },
  { number: 107, name: 'الماعون', persianName: 'ماعون', verses: 7 },
  { number: 108, name: 'الكوثر', persianName: 'کوثر', verses: 3 },
  { number: 109, name: 'الكافرون', persianName: 'کافرون', verses: 6 },
  { number: 110, name: 'النصر', persianName: 'نصر', verses: 3 },
  { number: 111, name: 'المسد', persianName: 'مسد', verses: 5 },
  { number: 112, name: 'الإخلاص', persianName: 'اخلاص', verses: 4 },
  { number: 113, name: 'الفلق', persianName: 'فلق', verses: 5 },
  { number: 114, name: 'الناس', persianName: 'ناس', verses: 6 },
]

export const TOTAL_QURAN_VERSES = 6236

// Get total verses for a campaign
export function getTotalVersesForCampaign(
  type: CampaignType,
  surahNumber?: number,
): number {
  if (type === CampaignType.General) {
    return TOTAL_QURAN_VERSES
  }

  if (type === CampaignType.Dua) {
    return 0
  }

  const surah = QURAN_SURAHS.find(s => s.number === surahNumber)
  return surah?.verses || 0
}
